### ISSUE TITLE
move server factory out of main and add unit tests

### ISSUE THREAD

**Issue by fgimenez** [giantswarm/ingress-operator#23]
After a deployment we were getting this failure:
```
~|⇒ kubectl logs pod/ingress-operator-3139664369-h67nn -n giantswarm
{"caller":"github.com/giantswarm/ingress-operator/service/service.go:66","debug":"creating ingress-operator with config: service.Config{Logger:(*micrologger.logger)(0xc420476c60), Flag:(*flag.Flag)(0xc4200190e0), Viper:(*viper.Viper)(0xc4200bc1e0), Description:\"The ingress-operator connects host cluster ingress controllers with guest cluster ingress controllers on a Giant Swarm Kubernetes host cluster.\", GitCommit:\"e9787b7671f6cd92e336f817a2ab87fa1a62b4a9\", Name:\"ingress-operator\", Source:\"https://github.com/giantswarm/ingress-operator\"}","time":"17-09-07 08:48:07.610"}
{"caller":"github.com/giantswarm/ingress-operator/vendor/github.com/giantswarm/operatorkit/client/k8s/k8s.go:99","debug":"creating in-cluster config","time":"17-09-07 08:48:07.610"}
{"caller":"github.com/giantswarm/ingress-operator/vendor/github.com/giantswarm/operatorkit/client/k8s/k8s.go:99","debug":"creating in-cluster config","time":"17-09-07 08:48:07.611"}
{"caller":"github.com/giantswarm/ingress-operator/vendor/github.com/giantswarm/operatorkit/client/k8s/k8s.go:99","debug":"creating in-cluster config","time":"17-09-07 08:48:07.612"}
{"caller":"github.com/giantswarm/ingress-operator/vendor/github.com/giantswarm/operatorkit/client/k8s/k8s.go:99","debug":"creating in-cluster config","time":"17-09-07 08:48:07.613"}
panic: transaction responder must not be empty: invalid config

goroutine 1 [running]:
github.com/giantswarm/ingress-operator/vendor/github.com/giantswarm/microkit/command/daemon.(*command).Execute(0xc4202b8720, 0xc42042b200, 0xc420345e80, 0x0, 0x2)
        /go/src/github.com/giantswarm/ingress-operator/vendor/github.com/giantswarm/microkit/command/daemon/command.go:128 +0x4d7
github.com/giantswarm/ingress-operator/vendor/github.com/giantswarm/microkit/command/daemon.(*command).Execute-fm(0xc42042b200, 0xc420345e80, 0x0, 0x2)
        /go/src/github.com/giantswarm/ingress-operator/vendor/github.com/giantswarm/microkit/command/daemon/command.go:75 +0x52
github.com/giantswarm/ingress-operator/vendor/github.com/spf13/cobra.(*Command).execute(0xc42042b200, 0xc420345de0, 0x2, 0x2, 0xc42042b200, 0xc420345de0)
        /go/src/github.com/giantswarm/ingress-operator/vendor/github.com/spf13/cobra/command.go:654 +0x299
github.com/giantswarm/ingress-operator/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420423200, 0x15bb5b4, 0x35, 0xc420476de0)
        /go/src/github.com/giantswarm/ingress-operator/vendor/github.com/spf13/cobra/command.go:729 +0x339
github.com/giantswarm/ingress-operator/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420423200, 0xc420423200, 0x1e)
        /go/src/github.com/giantswarm/ingress-operator/vendor/github.com/spf13/cobra/command.go:688 +0x2b
main.main()
        /go/src/github.com/giantswarm/ingress-operator/main.go:108 +0x83e
```
Turns out that `serverConfig.MicroServerConfig.TransactionResponder` was not set, it would be nice if we could move the server factory out of main in order to be able to unit test it.

**Comment by xh3b4sd** [comment]
1. I already started something similar a while ago. See https://github.com/giantswarm/draughtsman-eventer/blob/8a0bac0989aae465c524a3b8f951d815c890399e/main.go#L38. 

2. I also would like to add `error` to the server factory interface. See https://github.com/giantswarm/microkit/blob/9c50baa91bd1639e41bc5510b215d9d0801f94ca/command/daemon/spec.go#L10. 

3. Additionally some microservices have a `Boot` method that blocks forever. We should get used to additionally provide a `Shutdown` method in this case to be able to end boot. When these things are done we can easily write a test for the overall microservice initialization process. 

4. Also note that the transaction responder is probably something we want to get rid of. It started out as a cool idea but turned out to be not that cool.

**Comment by fgimenez** [comment]
Thanks for your notes @xh3b4sd I think i'll go for 2., will propose changes for adding an additional interface so that the current stuff keeps working, stay tuned :)

**Comment by xh3b4sd** [comment]
For my interest, what is the progress here? Can we track the work that has been done and that still has to be done? Should we maybe drop the issue and just boyscout as soon as we find some places where it is not yet done? Want to clean the board and I think we should either solve the issue or remove it.

**Comment by fgimenez** [comment]
No progress for quite a while /o\ Your boyscouting suggestion sgtm, closing now.
